### PR TITLE
Allow playbook to specify listen port(s) for nginx server.

### PR DESCRIPTION
**Pull request by max-b**
It turned out to be useful to me to be able to allow a playbook or host_var to specify the listen port(s).

Lemme know if it looks ok?

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/debops/ansible-etherpad/pull/7" target="_blank">ReviewNinja

**Comment by max-b** [comment]
It looks like the Travis CI build failed because of an issue with debops.nodejs.

I actually submitted a pr for that and you responded with some good ideas. I'll be following up on that at some point soon (when I get the chance).

**Comment by drybjed** [comment]
I'm not sure that this is a good location for this parameter. Without it, `debops.nodejs` depends on `debops.nginx` to enable/disable SSL or other ports. With it, you force `debops.nginx` to enable the listening on HTTP. Adding multiple listening ports to `nginx` is more involved, as it requires setting `default_server ipv6only=off` intelligently and opening ports in the firewall.

Can I ask what do you plan to do if you need different ports for each application? You should be able to use different applications on their subdomains instead, or each application can be deployed on different host / VM / LXC container.

If you need to change the default `nginx` listening port, I might look into that. Currently there's no obvious way to do it in `debops.nginx`, there could be a set of default variables for HTTP and HTTPS ports exposes in `defaults/` that would automatically configure the firewall. However, that will break the protocol (you need to specify port numbers each time), so I wonder, why do you need that?

**Comment by max-b** [comment]
it's definitely a strange situation. I can't actually create subdomains because I'm serving the webserver from a hostname with a locally-assigned dhcp domain name. Unfortunately, there's no support for wildcard (or really any) subdomain assignments with dnsmasq. So my server is stuck with just one fqdn and no chance of using subdomain.

The other problem is that I really don't want to have one giant nginx server block with a bunch of random sub-paths which aren't integrated into the rest of the provisioner.

What I'd like to do is use another nginx server block as a reverse proxy where hostname.domainname/pad would proxy  hostname.domainname:8081 and hostname.domainname/owncloud would proxy hostname.domainname:8082. Or something like that....

I'm not 100% following you on the issues you're describing... Wouldn't it be posible to do something like just adding:
```
listen_ssl: "{{ etherpad_ssl_listen_port if (etherpad_ssl_listen_port|d()) else ['[::]:443']  }}"
```

Or perhaps it would help to be more verbose with the variable names, so that the port that nginx is listening on and the port that etherpad is listening on are clearly different?

**Comment by drybjed** [comment]
Of course `dnsmasq` allows to create [wildcard domains](https://stackoverflow.com/questions/22313142/wildcard-subdomains-with-dnsmasq) pointed to specific IP address (you can add that using `dnsmasq_options` text block variable) or [multiple CNAMEs](https://github.com/debops/ansible-dnsmasq/blob/master/defaults/main.yml#L85-L89). Is that a `dnsmasq` instance on some kind of router? Try accessing it over console. If not, you should think about replacing it with `debops.dnsmasq` instead. :-)

OK, so instead of using subdomains, you want to create "one giant server block" with subdirectories instead, so that all applications are configured on one domain. It doesn't have to do much with changing listening ports though. Right now `debops.nginx` isn't designed to work that way, since adding another app to current server configuration via dependency would override the old one.

It could probably be added with some kind of subdirectory setup, but that would that some tinkering to write properly. I'll think if it can be done with current role. Right now I suggest that you look into fixing your `dnsmasq` problem instead.

**Comment by max-b** [comment]
"dnsmasq allows to create wildcard domains pointed to specific IP address", but I'd like any device to be able to connect, get a lease, and then be able to serve certain subdomains. Which I believe dnsmasq does not support. I also think that CNAMEs won't allow for the host providing subdomains - unless I'm missing something?

I don't actually want to have one "giant server block" - is there some reason I can't actually use one nginx server block to reverse proxy to the others?

**Comment by drybjed** [comment]
You can use one nginx server block to proxy to others, however they would need to be configured on separate ports... Which gives me an idea that each application could reserve its own internal socket in addition to normal HTTP and HTTPS ports... I need to look into it, but that will be later.

Let's say that you have a host named 'nexus'. If you configure CNAMEs in dnsmasq like this:
```
dnsmasq_cnames:
  'nexus': [ 'code', 'owncloud', 'pad' ]
```
the specified CNAMEs will point to the `nexus.example.org` host no matter what IP address it has. nginx then will pick up the CNAME you are requesting and serve the correct application.

**Comment by max-b** [comment]
Yeah I'd prefer to use subdomains, but the problem is that I can't list all of the possible hostnames of clients that might be connecting to the dnsmasq router. I want to allow a client with a set hostname to be able to get a fqdn with subdomains, which I'm pretty sure is impossible. But I'm more than happy to be proven otherwise :)

**Comment by max-b** [comment]
> You can use one nginx server block to proxy to others, however they would need to be configured on separate ports...

That's what I was hoping to achieve here?

**Comment by drybjed** [comment]
OK, so I'll look into adding socket support into, debops.nginx, that should
make this easier to do.
6 lip 2015 10:36 "max-b" <notifications@github.com> napisał(a):

**Comment by max-b** [comment]
It's not a big deal really - I think my branch will work just fine for me and I'm fine with keeping it up to date. 

I'm realizing that the issue here is that the ferm firewall rules would become an issue and that I haven't run into that yet because I have ferm turned off. I can take a more in-depth look at that when I get there, but yeah I see the issue as it stands. 

I can also take a look into the nginx unix socket listen stanza.

**Comment by drybjed** [comment]
In the new `debops.etherpad` v0.2.0 release, the `debops.nginx` configuration for the `debops.etherpad` role has been moved to the role default variables and can be easily modified via Ansible inventory. I'm closing this issue as resolved.

**Pull request closed without merging**
